V1 Implementation of Adaptive Environments (Tunnels)
amolchanov86/gym_art pull request #23
Opened 2020-11-16 18:53 UTC by SumeetBatra

Infrastructure code that allows us to change the shape and size of the environment during training. Can use this code to build rules in the future that decide how the environment changes over time based on statistics of the last N episodes, etc.

2020-11-22 03:10 UTC, alex-petrenko requested changes

2020-11-22 03:10 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +                 sim_steps=2, obs_repr='xyz_vxyz_R_omega', ep_time=7, obstacles_num=0, room_length=20, room_width=20, room_height=20,
Any reason to increase the size of the room initially?
I think 10 is a good value.

Or was 10 like a "radius" of the room, rather than the length of 1 side?

2020-11-22 03:10 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi_visualization.py
> +            viewpoint='chase', obs_hw=None, obstacle_mode='no_obstacles', room_dims=(10, 10, 10)
Here it's 10, 10, 10, but in the ctor it's 20, 20, 20
Let's keep it at 10,10,10 maybe?

2020-11-22 03:10 UTC, alex-petrenko commented on gym_art/quadrotor_multi/rendering3d.py
> +    corner2 = np.array([-x, y, 0])
Should this be [x, y, 0]?

2020-11-22 03:10 UTC, alex-petrenko commented on gym_art/quadrotor_multi/rendering3d.py
> +    # WTF IS THIS?????? lol
You have 8 vertices (4 points in vtop and 4 points in vbottom).
t is an array of triangles, for some reason they are 1-indexed (and then 1 is subtracted in the end, but ok, whatever)

To invert normals you will need to change the order of the vertices in triangles, as we discussed.
So 1,3,2 should become 1,2,3, etc... (I believe)

2020-11-24 18:59 UTC, SumeetBatra commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +                 sim_steps=2, obs_repr='xyz_vxyz_R_omega', ep_time=7, obstacles_num=0, room_length=20, room_width=20, room_height=20,
10 is the length of one side. I changed it to 20 just to give enough space for the drones to follow the bezier curves. It looked like the drones were going pretty close to the edge at just 10.

2020-11-24 19:01 UTC, SumeetBatra commented on gym_art/quadrotor_multi/quadrotor_multi_visualization.py
> +            viewpoint='chase', obs_hw=None, obstacle_mode='no_obstacles', room_dims=(10, 10, 10)
Maybe we should keep default to 20x3 for everything? just because while we are developing new methods and running experiments it might be better not to have to deal with the room bounds.

2020-11-30 11:46 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi_visualization.py
> +            viewpoint='chase', obs_hw=None, obstacle_mode='no_obstacles', room_dims=(10, 10, 10)
Don't care much either way, but I honestly don't see a reason to change this. The current value seems to work, why change it then? The first rule of programming

Another concern is that bigger numerical values like 20 and -20 might be hard for neural networks to work with, although with tanh activations that we use this might not be a problem

2020-12-10 14:22 UTC, alex-petrenko approved these changes

2020-12-10 14:23 UTC, merged