Added swarm versus mode and higher random forces for omega
amolchanov86/gym_art pull request #27
Opened 2020-12-22 22:50 UTC by tushartk

2020-12-29 00:01 UTC, alex-petrenko requested changes

2020-12-29 00:01 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quad_utils.py
> +    dyn2.omega += new_omega
Perfect!

2020-12-29 00:01 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +                 num_quads_in_vs_mode=None):
We don't need this parameter. Just assume that the number of agents in each group is num_agents / 2 (1 less in on of the groups if its not even)

2020-12-29 00:01 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quad_utils.py
> +    dyn2.omega += new_omega
Wait, I think this does not conserve the preservation of angular momentum. The second one should have a minus sign

2020-12-29 00:01 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quad_utils.py
> +    dyn2.omega += new_omega
Check if there's no bug in initial randomization. Fix the scaling (div by norm)

2020-12-29 01:06 UTC, tushartk commented on gym_art/quadrotor_multi/quad_utils.py
> +    dyn2.omega += new_omega
I think the scaling is correct according to Artem's implementation in random state initialization in `quadrotor_single.py` which is:
```
omega = np.random.uniform(low=-omega_max, high=omega_max, size=(3,))
omega_magn = np.random.uniform(low=0., high=omega_max)
omega = omega_magn / (np.linalg.norm(omega) + EPS) * omega
```

2020-12-29 03:06 UTC, SumeetBatra approved these changes

2020-12-29 03:06 UTC, SumeetBatra commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +                        env.goal = np.array(goal_1)
Not a huge deal since there's no computational bottleneck here, but personally I would do `goal_i = np.array([...])` from the start and `[env.goal = goal_i for env in self.envs[:mid]]`. Generally if you find yourself writing for-loops, see if you can't turn that sucker into a list comprehension or vectorize it somehow.

2020-12-29 03:34 UTC, tushartk commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +                        env.goal = np.array(goal_1)
I don't think list comprehension can be used to update an object's property, can it?

2020-12-29 03:52 UTC, SumeetBatra commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +                        env.goal = np.array(goal_1)
ah yea, not without using map(). Don't worry about it then. Looks good.

2020-12-30 16:46 UTC, alex-petrenko approved these changes
@tushartk I made a few modifications in the random omega function.
I believe this is how it should've been done.

In your last version you sampled a random direction with in range [max_omega/3, max_omega] which is not correct. Should have been [-max_omega, max_omega] or [-1,1]

2020-12-30 16:46 UTC, merged