Adaptive Envs, Bezier Curves, Room Dims
amolchanov86/gym_art pull request #28
Opened 2020-12-28 21:27 UTC by SumeetBatra

- Bezier curves are now randomly sampled in a while loop until a new goal pos that meets the constraints is found 
- Changed how room dims are defined and how room bounds checking works to be consistent across all files 
- Moved the floor of the room_box mesh to be slightly lower than the actual floor to prevent visual glitching 
- Purely random changing of the room dims during training and test time now supported

2020-12-30 17:42 UTC, alex-petrenko requested changes

2020-12-30 17:42 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +            new_length, new_width, new_height = np.random.randint(30, 30, 30)
How does this work? I've never seen randint used like this
https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html 
Docs say the first 3 arguments are low, high and size. So what does 30, 30, 30 do here?
I'm just curious how this works.

2020-12-30 17:42 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +        spacing_reward = hyperbolic_proximity_penalty(dists, dt)
I think this ought to have the coefficient if we're committing this to main branch.
Something similar to self.rew_coeff["quadcol_bin"] and it should be zero by default, at least until we find a good value

2021-01-04 20:05 UTC, SumeetBatra commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +            new_length, new_width, new_height = np.random.randint(30, 30, 30)
Oof, I must've been drunk or something when I wrote that. Should be `randint(0,31,3)`

2021-01-04 20:38 UTC, SumeetBatra commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +        spacing_reward = hyperbolic_proximity_penalty(dists, dt)
I've set the method's 'coeff; param default value to be np.inf which sets the penalty to be all zeros.

2021-01-07 07:41 UTC, alex-petrenko approved these changes

2021-01-07 07:42 UTC, alex-petrenko commented
@SumeetBatra or @tushartk can you resolve the collisions please? You are better qualified to do this than I am :)
Don't forget to test after the merge

2021-01-07 21:08 UTC, merged