A a new scenario that combines all other scenarios
amolchanov86/gym_art pull request #35
Opened 2021-01-15 02:45 UTC by Zhehui-Huang

I **refactored** the quadrotor_scenarios.py and add a **new** scenario that combine all other scenarios. And I also adjusted the name of some scenarios, so, please t **DON'T** forget to merge my pull request for sample-factory after you merging this pull request. Besides, I would like to provide more details about quadrotor_scenarios.py. There are 9 scenarios (including the new scenario, which named 'mix'). 
1. The first group of scenarios includes '**static_same_goal**' and '**dynamic_same_goal**', which means that all drones only have one goal, and the goal can be static/dynamic. In this group, formation is not the case, since formation_size=0.0.  
2. The second group of scenarios includes 'static_diff_goal' and 'dynamic_diff_goal', which means that all drones have their own goals, and the goal can be static/dynamic. In this group, there are 7 kinds of **formation**, which named 'circle_xz_vertical', 'circle_yz_vertical', 'circle_horizontal', 'sphere', 'grid_xz_vertical', 'grid_yz_vertical', 'grid_horizontal'. For example, 'circle_xz_vertical' means that the circle is formed on the plane of xz. 
3. The third group of scenarios includes 'circular_config', which means that the goals of all drones would be shuffled once all drones are settled at their own goals for one second, we should notice that I refactored this scenario, and currently, the formation does not only include a circle in horizontal, it also includes circle in xz/yz plane, grid in xz/yz/xy plane, and sphere. In this group, **same as the second group**, there are 7 kinds of formations. 
4.  The fourth group of scenarios includes 'ep_lissajous3D' and 'ep_rand_bezier', which is designed for the pursuit-evasion task. These two scenarios are much more similar to the dynamic_same_goal scenario, and the only difference is the moving trajectory of the goal. I have checked these two scenarios, but since I am not so familiar with the implementation of these two scenarios. Therefore, it would be better if @SumeetBatra could double-check these two scenarios.
5. The fifth group of scenarios includes 'swarm_vs_swarm'. **Same as the second group**, I extend the formation from only grid to circle, sphere and grid.
6. The sixth group of scenarios includes 'mix'. This scenario combines all scenarios that I mentioned above.

2021-01-15 20:48 UTC, SumeetBatra commented on gym_art/quadrotor_multi/quad_scenarios.py
> +        pass
I see how you're making the 'same goal' and 'diff goal' subclasses of a generic 'static goal' scenario, but I personally don't think this level of object inheritance is necessary. It doesn't give us any extra functionality as far as I can tell, and having all scenarios be subclasses of a generic quadrotor scenario is better for readability. Instead of having these be different classes, maybe having a class attribute like self.type = 'static/dynamic' would be better. 

This next bit is not as big of an issue, but I also think the naming convention here has become too redundant. For example, we have a QuadrotorScenario_... class that inherits from QuadrotorScenario super class that lives in a file called quad_scenarios lol.

2021-01-16 06:12 UTC, alex-petrenko requested changes
Okay, this is good!

I would do a few things slightly differently but overall it makes sense. My comments are mostly minor except this one:

I think for not we should only focus on scenarios that do not have obstacles. Our drones still collide with each other and obstacles add extra complexity that will make the debugging harder.


Why don't we disable all the obstacles for now and bring them back later when we figured this out.

2021-01-16 06:12 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +            obs = np.concatenate((obs, tmp_zero_arr), axis=1)
Why do we need a zero array if obstacle mode is "no obstacle"?

2021-01-16 06:12 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quad_scenarios.py
> +                                                                                               axis=0)  # add some velocity randomization = random magnitude * unit direction
This has very weird formatting, probably line breaks produced by your IDE

2021-01-16 06:12 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quad_scenarios.py
> +    def create_grids(self, goal_center_1, goal_center_2):
The name probably should be "create_formations" rather than grids

2021-01-16 06:12 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quad_scenarios.py
> +    def get_swarm_lowest_formation_size(self):
Lowest formation size should be 0. Why not? Why even have the low limit

2021-01-16 06:12 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quad_scenarios.py
> +    def get_swarm_lowest_formation_size(self):
I guess this is because they have to settle at their goals. GOt it

2021-01-16 06:19 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +            obs = np.concatenate((obs, tmp_zero_arr), axis=1)
That should be a mistake. I will fix that.

2021-01-16 06:20 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quad_scenarios.py
> +                                                                                               axis=0)  # add some velocity randomization = random magnitude * unit direction
I will fix that, no worries.

2021-01-16 06:20 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quad_scenarios.py
> +    def create_grids(self, goal_center_1, goal_center_2):
Good idea.

2021-01-16 06:26 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quad_scenarios.py
> +    def get_swarm_lowest_formation_size(self):
Yes, that's what I mean. for swarm_vs_swarm scenario, if we set the formation_size smaller than 2 * arm_length, then, all drones would never settle at their own goals.

2021-01-16 06:34 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quad_scenarios.py
> +        pass
I have ever thought to introduce `self.type = 'static/dynamic'`, but this parameter might increase the redundant. For example, in the ep_lissajous3D scenario. self.type is always dynamic. And the reason why I separate static_goal to static_same_goal and static_dynamic_goal is that for mix scenario, which combines all other scenarios, we have to generate formation_size randomly. If we merge the these two scenarios to one, then, it's hard for us to approach the static_same_goal scenario.
For the inherent stuff, I might try to create another script and put QuadrotorScenario__*** there.

2021-01-16 07:55 UTC, alex-petrenko approved these changes

2021-01-16 07:55 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quad_scenarios.py
> +            self.obstacle_number = 0
Ah, ok. Took me a few seconds to understand how this works...

2021-01-16 07:56 UTC, merged

2021-01-16 08:05 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quad_scenarios.py
> +            self.obstacle_number = 0
Yeah, it's a little bit hard to understand. These lines can make sure that we can use the command line to control the mode of the mix scenario. For example, if in the command line, the quads_mode=="no_obstacles", then, these lines can make sure all scenarios use "no_obstacle" mode.