Added formation size changes on key press
amolchanov86/gym_art pull request #40
Opened 2021-01-22 01:44 UTC by tushartk

2021-01-23 00:45 UTC, alex-petrenko requested changes

2021-01-23 00:45 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quad_scenarios.py
> +            self.update_formation_with_new_size(form_size)
Instead of adding this to every Scenario class, consider just adding a single method to the base class called something like `update_formation_size`.

In general, if you have to duplicate code like this, you are not doing it optimally.

2021-01-23 00:45 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quad_scenarios.py
> +            2 * np.pi / num_agents)
This is unnecessary reformatting. If you haven't changed the code please try not to edit it, such as extra spaces, newlines etc.
If you have an automatic code reformatter please make effort to disable it for existing (not new) code

2021-01-23 00:45 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quad_scenarios.py
> +        infos, rewards = self.scenario.step(infos=infos, rewards=rewards, pos=pos, form_size=form_size)
This is where we can update the formation size with just one line of code.

2021-01-23 00:45 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +        self.quads_formation_size = quads_formation_size
I believe this will be negative by default. If it is negative, we should use the default formation size from the scenario rather than value -1.0

2021-01-23 00:45 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi_visualization.py
> +
So this will also increase/decrease the formation size in jumps. Can we also make this smooth, similar to camera controls in Zhehui's last PR?

2021-01-24 20:46 UTC, tushartk commented on gym_art/quadrotor_multi/quad_scenarios.py
> +            2 * np.pi / num_agents)
Was by mistake. Sorted it out.

2021-01-24 22:26 UTC, tushartk commented on gym_art/quadrotor_multi/quad_scenarios.py
> +            self.update_formation_with_new_size(form_size)
`update_formation_size`  has been defined in the base class itself

2021-01-26 23:56 UTC, alex-petrenko approved these changes
I think this is okay for now, should work. We can polish it later.

2021-01-26 23:56 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quad_scenarios.py
> +
As I mentioned, I believe this is unnecessary. Static goal scenarios still have a formation, just it's default size is 0.

2021-01-26 23:56 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quad_scenarios.py
> +            self.reset()
Why do we need to call reset() here and not for the other scenarios?

2021-01-26 23:56 UTC, merged