Make sure all goal positions are 0.25 meters above the floor
amolchanov86/gym_art pull request #41
Opened 2021-01-22 07:53 UTC by Zhehui-Huang

2021-01-23 01:01 UTC, alex-petrenko requested changes

2021-01-23 01:01 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi_visualization.py
> +        self.center_list_id = 0
Zhehui, what is this?

2021-01-23 01:01 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi_visualization.py
>          if self.viepoint == 'global':
Misprint here, should be `Viewpoint`

2021-01-23 01:01 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi_visualization.py
> +        self.center_list_id = 0
It would help to write a comment here if you just have hardcoded values like this. 
I suspect this is corners of the room or something like that.
But the room size can change in different scenarios. I am not convinced that we even need this tbh

2021-01-23 01:01 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi_visualization.py
> +            self.keys[key.LEFT] = 1
Now it seems like we don't need the function `window_on_key_press` at all.
I think keyHandler provides the state of the keyboard whenever we need it, right?

Why do we need to do practically the same thing here and in `window_smooth_change_view`?

2021-01-23 01:01 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi_visualization.py
> +        self.keys = key.KeyStateHandler()
This also seems redundant.
We can just query key.KeyStateHandler() whenever we need it. Am I wrong?
(Good job on finding this method BTW, I didn't know it exists)

See example here: https://pyglet.readthedocs.io/en/latest/programming_guide/keyboard.html#remembering-key-state

2021-01-23 01:01 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi_visualization.py
> +        elif self.keys[key.DOWN]:
The step sizes are currently fixed hardcoded values, am I right?
So depending on how fast the rendering is we will have different effect from pressing the buttons.
I.e. at 60FPS the rotation will be 3 times faster than at 20 FPS.
Usually when you make interactive apps like this you should always measure `dt` time passed since last frame and multiply your fixed step by the `dt` to provide consistent feedback.

This is not crucial for now but should be a very easy fix.

2021-01-26 06:32 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quadrotor_multi_visualization.py
> +        self.center_list_id = 0
I set this just to make it possible to look at the whole swarm when we run pursuit-evasion scenarios. Do you have any suggestions for the global camera of pursuit-evasion scenario?

2021-01-26 23:57 UTC, alex-petrenko approved these changes
I think this should work! Good job!

2021-01-27 00:02 UTC, alex-petrenko commented
I resolved the merge conflict, seemed fairly trivial. But still please test if everything works after the merge.

2021-01-27 00:11 UTC, merged

2021-01-27 00:20 UTC, Zhehui-Huang commented
Sure, I will test it.