Introduce curriculum
amolchanov86/gym_art pull request #45
Opened 2021-02-06 00:40 UTC by Zhehui-Huang

2021-02-08 01:28 UTC, tushartk approved these changes
Seems good

2021-02-09 16:38 UTC, SumeetBatra commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +        if self.curriculum_mode != "none":
is this supposed to be the 'epsilon-greedy' mode? If so, it should be more explicit. i.e. 
`if self.curriculum_mode == 'epsilon-greedy:
    ...
elif self.curriculum_mode == "UCB1":
    ...
elif self.curriculum_mode == "none":
   ...
else:
    NotImplementedError '
`

2021-02-09 16:45 UTC, SumeetBatra commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +            assert self.quads_mode == "mix"
why are we asserting that the scenario needs to be "mix" here? Mix is a single scenario that randomly samples all other ones. For curriculum, we should be sampling individual scenarios based on some statistics.

2021-02-09 17:01 UTC, SumeetBatra commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +            self.crash_list = []
Could you explain what this is doing? If I had to guess it looks like this is calculating the avg num crashes over the last 20 episodes and seeing if it is < 1.0 (which seems fairly aggressive to me. I don't think we even dip below 1.0 during training until ~500M steps)

Personally, I believe we should try to activate curriculum once the position reward is less than some threshold, since this is the best indicator of whether the drones are flying or not. The drones can be skirting around on the floor and not colliding, but this doesn't mean they've learned how to fly. 

Also, it would be nice in the future if you could leave some docstring like comments just for readability and future-proofing :)

2021-02-09 17:03 UTC, SumeetBatra commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +                    self.curriculum_episode_num += 1
same comments as before. Should be more explicity about what curriculum_mode is and not sure why we are asserting that quads_mode = "mix"

2021-02-09 17:05 UTC, SumeetBatra requested changes
Looks good for the most part, but a few minor details I'm confused on. Have you tested this to make sure it's working as intended? I haven't seen any curriculum results in Slack unless I missed something. Would prefer if you tested this locally and reported on the results to make sure there aren't any bugs since it's hard for me to verify from just looking at the GitHub diffs.

2021-02-09 20:17 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +        if self.curriculum_mode != "none":
If I program like this, then, there will have many duplicate codes between epsilon-greedy and UCB1.

2021-02-09 20:20 UTC, SumeetBatra commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +        if self.curriculum_mode != "none":
Initialize the duplicate code outside the if-else block

2021-02-09 20:22 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +        if self.curriculum_mode != "none":
```
if self.curriculum_mode == "epsilon-greedy": 
    pass
elif self.curriculum_mode == "UCB1":
    self.curriculum_episode_num = 0
elif self.curriculum_mode == "none":
    pass
else:
    NotImplementedError
```
Some other code for curriculum

2021-02-09 20:25 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +            assert self.quads_mode == "mix"
This part of the code is in the init function for multi_env, right? The "mix" here, means we pass quads_mode=mix through the command line. I do this just want to make sure we use the curriculum based on the mix scenario, rather than any other single scenario.

2021-02-09 20:25 UTC, SumeetBatra commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +        if self.curriculum_mode != "none":
if only that one line `self.curriculum_episode_num = 0` is dependent on the curriculum mode, then I would remove the entire if-else block and set that line regardless. Worst case is we do not use UCB1 and that variable is never used.

2021-02-09 20:27 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +            self.crash_list = []
We start the curriculum after drones learn how to fly (or the reward of crash is lower than 1.0). Since it doesn't make sense to start the curriculum when drones don't know how to fly.
Yeah, I will add some comments here.

2021-02-09 20:30 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +                    self.curriculum_episode_num += 1
The answer is the same as above. I can change the way of programming if you think use 'epsilon=greedy' and 'UCB1' to replace !='none' can make our code better.

2021-02-09 20:33 UTC, SumeetBatra commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +            assert self.quads_mode == "mix"
Ok I see what you did. I thought we would create a separate scenario class for curriculum. This approach overloads the use of the mixed scenario. I have a slight preference for creating separate scenarios for clarity, but since it is already implemented this way, I guess it's fine.

2021-02-15 02:42 UTC, closed without merging