Attention, Tunnel Env, Bug Fixes
amolchanov86/gym_art pull request #47
Opened 2021-02-11 01:48 UTC by SumeetBatra

- General get_obs_rel function that includes attention 
- Bug fix where room dims wouldn't change during evaluation time 
- Tunnel scenario (not included in mixed scenario for now, but can if we want to down the line)

2021-02-11 04:16 UTC, Zhehui-Huang requested changes
I basically okay with your changes. My only question is that have you tested your changes? Sometimes, it's not easy to find the bugs until we run some experiments.

2021-02-11 04:16 UTC, Zhehui-Huang commented on gym_art/quadrotor_multi/quadrotor_single.py
> +            "vxyzr": [-2*self.dynamics.vxyz_max * np.ones(3), 2*self.dynamics.vxyz_max * np.ones(3)],
I don't think we should change vxyz and vxyzr. They are not the relative velocity

2021-02-11 15:56 UTC, SumeetBatra commented on gym_art/quadrotor_multi/quadrotor_single.py
> +            "vxyzr": [-2*self.dynamics.vxyz_max * np.ones(3), 2*self.dynamics.vxyz_max * np.ones(3)],
We use them to do clipping on relative velocity

2021-02-11 15:58 UTC, SumeetBatra commented on gym_art/quadrotor_multi/quadrotor_single.py
> +            "vxyzr": [-2*self.dynamics.vxyz_max * np.ones(3), 2*self.dynamics.vxyz_max * np.ones(3)],
Whoops, I think I misread the code. I'll change this back

2021-02-11 16:00 UTC, SumeetBatra commented
> I basically okay with your changes. My only question is that have you tested your changes? Sometimes, it's not easy to find the bugs until we run some experiments.

All of these have been tested locally with train and evaluation scripts. I've started a full run on the server but it hasn't finished yet

2021-02-15 02:59 UTC, alex-petrenko approved these changes

2021-02-15 02:59 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +        elif self.swarm_obs == 'attn':
This name should be explicit and descriptive

2021-02-15 02:59 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_single.py
> +            "vxyz": [self.dynamics.vxyz_max * np.ones(3), self.dynamics.vxyz_max * np.ones(3)],
bug

2021-02-15 04:26 UTC, merged