Added textured obstacles and flags for rendering acceleration arrows and trails
amolchanov86/gym_art pull request #65
Opened 2021-03-04 02:57 UTC by tushartk

2021-03-04 05:57 UTC, alex-petrenko commented
Can you please fix Travis first? It seems to be failing. I know this is probably not because of your PR

2021-03-04 06:03 UTC, alex-petrenko requested changes

2021-03-04 06:03 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi.py
> +                 viz_traces=40, viz_trace_nth_step=1):
isn't 40 a bit too much? was it 25 before?

2021-03-04 06:03 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi_visualization.py
> +            elif item.shape == 'textured_sphere':
Textured shape is not a new shape. It should be just a new visualization mode.
Honestly, I think it just looks better so it can just replace a regular sphere

2021-03-04 06:03 UTC, alex-petrenko commented on gym_art/quadrotor_multi/quadrotor_multi_visualization.py
> +                obstacle_transform = r3d.transform_and_dual_color(np.eye(4), (0, 0, 1), (1, 1, 0),
oh, so it's not textured :D
I see
cool hack, and I am fine with it as long as it works, although still I don't understand why texturing is so hard :)

https://gist.github.com/davepape/7324958

2021-03-04 08:23 UTC, tushartk commented
Weirdly it's from this PR where the tests start to fail - https://github.com/amolchanov86/gym_art/commit/70d8ad3cd92b35714396ff80c5e63edc2de4140c
Not able to pinpoint what exactly is causing this

2021-03-07 02:43 UTC, alex-petrenko commented
We have to figure it out and fix the tests.

Maybe I missed an import somewhere? What are the errors in Travis? Anything
useful?


чт, 4 мар. 2021 г. в 00:24, Tushar K <notifications@github.com>:

> Weirdly it's from this PR where the tests start to fail - 70d8ad3
> <https://github.com/amolchanov86/gym_art/commit/70d8ad3cd92b35714396ff80c5e63edc2de4140c>
> Not able to pinpoint what exactly is causing this
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/amolchanov86/gym_art/pull/65#issuecomment-790422748>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABJ6HL4EVGIIGLDJF5XEDATTB47R7ANCNFSM4YSM2YAA>
> .
>

2021-03-07 02:59 UTC, tushartk commented
```
======================================================================
ERROR: test_replay (gym_art.quadrotor_multi.tests.test_multi_env.TestReplayBuffer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/tests/test_multi_env.py", line 117, in test_replay
    env.render()
  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/gym/core.py", line 240, in render
    return self.env.render(mode, **kwargs)
  File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/quadrotor_multi.py", line 576, in render
    self.scene.update_env(self.room_dims)
  File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/quadrotor_multi_visualization.py", line 114, in update_env
    self._make_scene()
  File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/quadrotor_multi_visualization.py", line 185, in _make_scene
    world.build(batch)
  File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/rendering3d.py", line 259, in build
    self._build_children(batch)
  File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/rendering3d.py", line 247, in _build_children
    c.build(batch, self.pyg_grp)
  File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/rendering3d.py", line 298, in build
    c.build(batch, ordering)
  File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/rendering3d.py", line 388, in build
    self.pyg_grp = _PygTexture(tex=self.tex,
  File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/rendering3d.py", line 489, in __init__
    glGetFloatv(GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT, anisotropy)
  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/pyglet/gl/lib.py", line 107, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid enumerant'
```
This is what travis shows

2021-03-07 03:13 UTC, alex-petrenko commented
If you are confident that this exact error appeared when I changed OpenGL
imports to not require xvfb during training, then it's probably caused by
something like order in which the modules are imported.
In which case the easiest fix seems to be to use the old import at the top
of the file but only in Travis.
You can see my commit diff to see how imports were changed.

Let me know if this works

сб, 6 мар. 2021 г. в 18:59, Tushar K <notifications@github.com>:

> ======================================================================
> ERROR: test_replay (gym_art.quadrotor_multi.tests.test_multi_env.TestReplayBuffer)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/tests/test_multi_env.py", line 117, in test_replay
>     env.render()
>   File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/gym/core.py", line 240, in render
>     return self.env.render(mode, **kwargs)
>   File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/quadrotor_multi.py", line 576, in render
>     self.scene.update_env(self.room_dims)
>   File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/quadrotor_multi_visualization.py", line 114, in update_env
>     self._make_scene()
>   File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/quadrotor_multi_visualization.py", line 185, in _make_scene
>     world.build(batch)
>   File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/rendering3d.py", line 259, in build
>     self._build_children(batch)
>   File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/rendering3d.py", line 247, in _build_children
>     c.build(batch, self.pyg_grp)
>   File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/rendering3d.py", line 298, in build
>     c.build(batch, ordering)
>   File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/rendering3d.py", line 388, in build
>     self.pyg_grp = _PygTexture(tex=self.tex,
>   File "/home/travis/build/amolchanov86/gym_art/gym_art/quadrotor_multi/rendering3d.py", line 489, in __init__
>     glGetFloatv(GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT, anisotropy)
>   File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/pyglet/gl/lib.py", line 107, in errcheck
>     raise GLException(msg)
> pyglet.gl.lib.GLException: b'invalid enumerant'
>
> This is what travis shows
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/amolchanov86/gym_art/pull/65#issuecomment-792182824>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABJ6HL7K7S7TEZYJO7YLK3DTCLTYLANCNFSM4YSM2YAA>
> .
>

2021-03-11 17:24 UTC, alex-petrenko approved these changes
Okay I guess we can fix the test bug later

2021-03-11 17:24 UTC, merged